apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boskos-janitor
  labels:
    app: boskos-janitor
spec:
  replicas: 1  # one canonical source of resources
  template:
    metadata:
      labels:
        app: boskos-janitor
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: boskos-janitor
        image: gcr.io/k8s-testimages/janitor:v20170711-1a80241f
        args:
        - --service-account=/etc/service-account/service-account.json
        volumeMounts:
        - mountPath: /etc/service-account
          name: service
          readOnly: true
      volumes:
      - name: service
        secret:
          secretName: service-account
